### PR TITLE
WG3 Tentative program

### PR DESCRIPTION
**Pull request by muhammad-usama-sardar**

### CODE REVIEW

**Comment by muhammad-usama-sardar** [comment]
@fblanqui the page (https://europroofnet.github.io/wg3-dresden24-program/) does not seem to be live. Did I miss something? Could you please have a look and fix it?

**Comment by fblanqui** [comment]
done

**Comment by fblanqui** [comment]
you forgot the file extension .md

**Comment by fblanqui** [comment]
but you should add a link to the program page from the meeting page at some point

**Comment by muhammad-usama-sardar** [comment]
> you forgot the file extension .md

oh I see, thanks. 

> but you should add a link to the program page from the meeting page at some point

Sure, will do with the next PR.

**Pull request merged**
