### PR TITLE
wg6 leuven

### PR DESCRIPTION
**Pull request by anuyts**
Info on WG6 meeting in Leuven.

### CODE REVIEW

**Comment by fblanqui** [comment]
Hi. Thanks for the PR but we need to wait for the validation of the work and budget plan by COST and the MC to merge it, hopefully in 2 or 3 weeks maximum.

**Comment by fblanqui** [comment]
Hi Andreas. I added https://github.com/EuroProofNet/europroofnet.github.io/blob/main/_pages/WG6/Leuven/admin.md . This is a check/todo list we set up for every meeting. Please follow it.
You also need to fix a few things in your PR: the official dates of the meeting are April 4-5 (2 days). For people to apply for funding, they need to know the dates that are reimbursed (April 4-5) and the daily allowance (140 euros).

**Comment by anuyts** [comment]
Will people who attend both days receive the daily allowance 2 times or 2+1 times?

**Comment by fblanqui** [comment]
It depends on the days and times of arrival and departure. Please check the COST annotated rules https://www.cost.eu/Annotated_Rules_for_COST_Actions_C page 85 and 92 for LOS.

**Comment by fblanqui** [comment]
Thanks!

**Pull request merged**
